# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1847e2def24532d47165cc13e9725389315c3c1adfaf03836868aa41c88b385ccf002f8e82e195466c4f1c1d7abf157072bff45b9ddc54414b878eb017c6343
  s3:
    access_key_id: AKIAIAK2ZFMBZKG6URMQ
    secret_access_key: "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"
    bucket: videopage7-dev
    region: eu-west-1
  panda:
    access_key: 8ba1bda810b444406b18
    secret_key: 8d54774cf64d748ea3c0
    cloud_id: 07ed6434686c39f07c399064c1573731
    api_host: "api-eu.pandastream.com"
  bonofa:
    app_id: 9123315e71131de37a8a829569a532ff442b49b878c09d9c3179fcf275933d42
    secret_key: e4da7a8dd5fb5c727d860e2a06b3bffd7eb70e13eb4a9ece36199fb80b45e1f5
    site_url: "http://biao.sevendevs.de"

test:
  secret_key_base: bb22ad95b631a83ba0ee8ec0c6bbd0927372981f8f4c06fdf841affd65225e1195282bfd2529af0b5d1cacab3714c1677bb3257a19cb3b75139fa72a91ea69a2
  panda:
    access_key_id: AKIAIAK2ZFMBZKG6URMQ
    secret_access_key: "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"
    bucket: videopage7-dev
    region: eu-west-1
  bonofa:
    app_id: 9123315e71131de37a8a829569a532ff442b49b878c09d9c3179fcf275933d42
    secret_key: e4da7a8dd5fb5c727d860e2a06b3bffd7eb70e13eb4a9ece36199fb80b45e1f5
    site_url: "http://biao.sevendevs.de"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  panda:
    access_key: <%= ENV["PANDA_ACCESS_KEY_ID"] %>
    secret_key: <%= ENV["PANDA_SECRET_ACCESS_KEY"] %>
    cloud_id: <%= ENV["PANDA_COULD_ID"] %>
    api_host: "api-eu.pandastream.com"
  cube7:
    app_id: 1f50c3ca1b9f6ef2bb5250046750b7d65168fe31aaee91b91b0d3b006ce9ccd1
    secret_key: 0cc271e55108b843c8f8b3fbc5ae72fae961b9f4863245a49aef7e165e37a8d9
    site_url: "http://cube7.sevendevs.de"
  bonofa:
    app_id: 5582033167c4ac3554103bf6e44e46a6c05215fdb273347a444387342cc2cbd9
    secret_key: 108624a21282a9fd7cda39a801873ecbed78315baeedec5efa42d9e49987368d
    site_url: "http://biao.sevendevs.de"